name: Bet Log Processor

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - '.github/workflows/bet-log-processor.yml'

# Add explicit permissions for the workflow
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  process-bet-logs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Fetch Torn City Logs
      id: fetch-logs
      run: |
        echo "🔄 Fetching Torn City logs..."
        
        # Fetch logs from Torn API
        LOGS_RESPONSE=$(curl -s "https://api.torn.com/user/?selections=log&key=${{ secrets.TORN_API_KEY }}&comment=BetLogProcessor")
        
        # Check if API call was successful
        if echo "$LOGS_RESPONSE" | grep -q '"error"'; then
          echo "❌ Error fetching logs:"
          echo "$LOGS_RESPONSE"
          exit 1
        fi
        
        echo "✅ Successfully fetched logs"
        echo "logs_response<<EOF" >> $GITHUB_OUTPUT
        echo "$LOGS_RESPONSE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Process and Filter Bet Logs
      id: process-logs
      run: |
        echo "🔍 Processing and filtering bet logs..."
        
        # Create data directory if it doesn't exist
        mkdir -p data
        
        # Process logs using the dedicated script
        node scripts/process-bet-logs.js "${{ steps.fetch-logs.outputs.logs_response }}"
        
    - name: Create Bet Confirmation Summary
      id: create-summary
      run: |
        echo "📊 Creating bet confirmation summary..."
        
        # Simple summary without complex JSON parsing
        if [ -f "data/bet-logs.json" ]; then
          echo "✅ Bet logs data file exists and has been processed"
        else
          echo "No bet-logs.json found"
        fi
        
    - name: Commit and Push Changes
      run: |
        echo "💾 Committing and pushing changes..."
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add changes
        git add data/bet-logs.json
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          # Commit changes
          git commit -m "🤖 Automated bet log processing - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          
          # Push changes with proper authentication
          git push
          echo "✅ Changes committed and pushed"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Summary Comment
      if: github.event_name == 'workflow_dispatch'
      uses: actions/github-script@v7
      with:
        script: |
          console.log('✅ Bet log processing completed successfully');
          
          // Simple comment without complex JSON parsing
          const comment = `
          ## 🤖 Bet Log Processing Summary
          
          **✅ Status:** Processing completed successfully
          
          The automated bet log processor has run and updated the betting data.
          Check the data/bet-logs.json file for details.
          `;
          
          // Only create comment if this is triggered manually
          if (context.eventName === 'workflow_dispatch') {
            console.log('Creating summary comment...');
          } 