name: Betting Wars Selection

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-betting-wars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install mongodb axios
      - name: Fetch wars from Torn API
        env:
          TORN_API_KEY: ${{ secrets.TORN_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node scripts/fetch-wars.js
      - name: Select betting wars
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node scripts/select-betting-wars.js
      - name: Commit and push betting wars
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/betting-wars.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update betting wars selection"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}