name: Log Puller

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  pull-logs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install axios
      
    - name: Pull and filter logs
      env:
        TORN_API_KEY: ${{ secrets.BOOKIE_API_KEY }}
      run: node scripts/log-puller.js
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/filtered-logs.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update filtered logs - $(date)"
        git push 